### ISSUE TITLE
Importers are failing to run on staging.

### ISSUE THREAD

**Issue by drteeth** [bikebrigade/dispatch#9]
```
14:57:15.018 [error] GenServer #PID<0.18606.0> terminating
** (RuntimeError) Missing enviornment variable IMPORTER_CHECKIN_URL
    (bike_brigade 0.1.0) lib/bike_brigade/importers/runner.ex:30: BikeBrigade.Importers.Runner.honeybadger_checkin/0
    (bike_brigade 0.1.0) lib/bike_brigade/importers/runner.ex:18: BikeBrigade.Importers.Runner.handle_info/2
    (stdlib 3.16) gen_server.erl:695: :gen_server.try_dispatch/4
    (stdlib 3.16) gen_server.erl:771: :gen_server.handle_msg/6
    (stdlib 3.16) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: :run_importers
```

**Comment by mveytsman** [comment]
I'm not sure we should be running the mailchimp importer on staging -- but this opens up bigger questions  do we want to be pulling live data etc.
